[package]
name = "ch6-create-destroy-objects-in-a-heap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston2d-graphics = "0.44"
piston_window = "0.131"
rand = "0.8"
